### ISSUE TITLE
AppiOS/MTOUCH: Error MT3001: Could not AOT the assembly 

### ISSUE THREAD

**Issue by vandenbrakel** [ManagedBass/ManagedBass#41]
Not sure if this is a managedBass issue or a libbass issue. I can build debug on device and simulator,
Ik can build release on simulator. But when I try to build release on device I get this error. (or archiving for publishing)

AppiOS/MTOUCH: Error MT3001: Could not AOT the assembly 
/AppiOS/obj/iPhone/Release/mtouch-cache/64/Build/AppiOS.exe' (MT3001) (AppiOS)

Any idea's?

Thanks in advance.

**Comment by MathewSachin** [comment]
Not sure about this error. But, have you followed the [Getting Started - iOS](https://github.com/ManagedBass/Home/blob/master/docs/Getting%20Started/iOS.md) guide.

You have to apply some MTOUCH arguments and also there is a special format for callback functions.

**Comment by MathewSachin** [comment]
I would like to know if you are using any addons like `ManagedBass.Fx` or `ManagedBass.Mix`.

**Comment by vandenbrakel** [comment]
Yes, ManagedBass.Fx is also in the project.

**Comment by MathewSachin** [comment]
I released updated to `ManagedBass` and `ManagedBass.Fx` packages. Please try them.

**Comment by vandenbrakel** [comment]
ManagedBass 2.04 and ManagedBass.fx 2.01 did not resolve the AOT issue.

**Comment by MathewSachin** [comment]
Closing since fixed
